### PR TITLE
Update api.js

### PR DESCRIPTION
**Pull request by abossard**

### CODE REVIEW

**Comment by timmson** [comment]
hi guys, what issue does it solve? could you share context?

**Comment by kennyyuen** [comment]
This fixed my issue on calling processCommand with Error
```
\node_modules\xmlbuilder\lib\XMLStringifier.js:213
        throw new Error("Invalid character in name");
              ^

Error: Invalid character in name
```

**Comment by timmson** [comment]
Ok. i ll merge it and issue new version, thx!

**Comment by timmson** [comment]
Closes #17

**Pull request closed without merging**
